spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: postgres
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver

# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
customer:
  product:
    status:
      - 初始
      - 中试
      - 试产
      - 量产
      - 即将作废
      - 已作废
      - 已退市